// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { KeyPairArgs } from "./keyPair";
export type KeyPair = import("./keyPair").KeyPair;
export const KeyPair: typeof import("./keyPair").KeyPair = null as any;
utilities.lazyLoad(exports, ["KeyPair"], () => require("./keyPair"));

export { KeyPairListArgs } from "./keyPairList";
export type KeyPairList = import("./keyPairList").KeyPairList;
export const KeyPairList: typeof import("./keyPairList").KeyPairList = null as any;
utilities.lazyLoad(exports, ["KeyPairList"], () => require("./keyPairList"));

export { KeyPairPatchArgs } from "./keyPairPatch";
export type KeyPairPatch = import("./keyPairPatch").KeyPairPatch;
export const KeyPairPatch: typeof import("./keyPairPatch").KeyPairPatch = null as any;
utilities.lazyLoad(exports, ["KeyPairPatch"], () => require("./keyPairPatch"));

export { VirtualMachineImageArgs } from "./virtualMachineImage";
export type VirtualMachineImage = import("./virtualMachineImage").VirtualMachineImage;
export const VirtualMachineImage: typeof import("./virtualMachineImage").VirtualMachineImage = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImage"], () => require("./virtualMachineImage"));

export { VirtualMachineImageListArgs } from "./virtualMachineImageList";
export type VirtualMachineImageList = import("./virtualMachineImageList").VirtualMachineImageList;
export const VirtualMachineImageList: typeof import("./virtualMachineImageList").VirtualMachineImageList = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImageList"], () => require("./virtualMachineImageList"));

export { VirtualMachineImagePatchArgs } from "./virtualMachineImagePatch";
export type VirtualMachineImagePatch = import("./virtualMachineImagePatch").VirtualMachineImagePatch;
export const VirtualMachineImagePatch: typeof import("./virtualMachineImagePatch").VirtualMachineImagePatch = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImagePatch"], () => require("./virtualMachineImagePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:harvesterhci.io/v1beta1:KeyPair":
                return new KeyPair(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:KeyPairList":
                return new KeyPairList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:KeyPairPatch":
                return new KeyPairPatch(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImage":
                return new VirtualMachineImage(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImageList":
                return new VirtualMachineImageList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImagePatch":
                return new VirtualMachineImagePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "harvesterhci.io/v1beta1", _module)
