// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { NetworkAttachmentDefinitionArgs } from "./networkAttachmentDefinition";
export type NetworkAttachmentDefinition = import("./networkAttachmentDefinition").NetworkAttachmentDefinition;
export const NetworkAttachmentDefinition: typeof import("./networkAttachmentDefinition").NetworkAttachmentDefinition = null as any;
utilities.lazyLoad(exports, ["NetworkAttachmentDefinition"], () => require("./networkAttachmentDefinition"));

export { NetworkAttachmentDefinitionListArgs } from "./networkAttachmentDefinitionList";
export type NetworkAttachmentDefinitionList = import("./networkAttachmentDefinitionList").NetworkAttachmentDefinitionList;
export const NetworkAttachmentDefinitionList: typeof import("./networkAttachmentDefinitionList").NetworkAttachmentDefinitionList = null as any;
utilities.lazyLoad(exports, ["NetworkAttachmentDefinitionList"], () => require("./networkAttachmentDefinitionList"));

export { NetworkAttachmentDefinitionPatchArgs } from "./networkAttachmentDefinitionPatch";
export type NetworkAttachmentDefinitionPatch = import("./networkAttachmentDefinitionPatch").NetworkAttachmentDefinitionPatch;
export const NetworkAttachmentDefinitionPatch: typeof import("./networkAttachmentDefinitionPatch").NetworkAttachmentDefinitionPatch = null as any;
utilities.lazyLoad(exports, ["NetworkAttachmentDefinitionPatch"], () => require("./networkAttachmentDefinitionPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:k8s.cni.cncf.io/v1:NetworkAttachmentDefinition":
                return new NetworkAttachmentDefinition(name, <any>undefined, { urn })
            case "kubernetes:k8s.cni.cncf.io/v1:NetworkAttachmentDefinitionList":
                return new NetworkAttachmentDefinitionList(name, <any>undefined, { urn })
            case "kubernetes:k8s.cni.cncf.io/v1:NetworkAttachmentDefinitionPatch":
                return new NetworkAttachmentDefinitionPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "k8s.cni.cncf.io/v1", _module)
