// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CloudinitSecret extends pulumi.CustomResource {
    /**
     * Get an existing CloudinitSecret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudinitSecretState, opts?: pulumi.CustomResourceOptions): CloudinitSecret {
        return new CloudinitSecret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harvester:index/cloudinitSecret:CloudinitSecret';

    /**
     * Returns true if the given object is an instance of CloudinitSecret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudinitSecret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudinitSecret.__pulumiType;
    }

    public readonly cloudinitSecretId!: pulumi.Output<string>;
    /**
     * Any text you want that better describes this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    public /*out*/ readonly message!: pulumi.Output<string>;
    /**
     * A unique name
     */
    public readonly name!: pulumi.Output<string>;
    public readonly namespace!: pulumi.Output<string | undefined>;
    public readonly networkData!: pulumi.Output<string | undefined>;
    public readonly networkDataBase64!: pulumi.Output<string | undefined>;
    public /*out*/ readonly state!: pulumi.Output<string>;
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly timeouts!: pulumi.Output<outputs.CloudinitSecretTimeouts | undefined>;
    public readonly userData!: pulumi.Output<string | undefined>;
    public readonly userDataBase64!: pulumi.Output<string | undefined>;

    /**
     * Create a CloudinitSecret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CloudinitSecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudinitSecretArgs | CloudinitSecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudinitSecretState | undefined;
            resourceInputs["cloudinitSecretId"] = state ? state.cloudinitSecretId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["message"] = state ? state.message : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["namespace"] = state ? state.namespace : undefined;
            resourceInputs["networkData"] = state ? state.networkData : undefined;
            resourceInputs["networkDataBase64"] = state ? state.networkDataBase64 : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["userData"] = state ? state.userData : undefined;
            resourceInputs["userDataBase64"] = state ? state.userDataBase64 : undefined;
        } else {
            const args = argsOrState as CloudinitSecretArgs | undefined;
            resourceInputs["cloudinitSecretId"] = args ? args.cloudinitSecretId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["namespace"] = args ? args.namespace : undefined;
            resourceInputs["networkData"] = args ? args.networkData : undefined;
            resourceInputs["networkDataBase64"] = args ? args.networkDataBase64 : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["userData"] = args ? args.userData : undefined;
            resourceInputs["userDataBase64"] = args ? args.userDataBase64 : undefined;
            resourceInputs["message"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudinitSecret.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CloudinitSecret resources.
 */
export interface CloudinitSecretState {
    cloudinitSecretId?: pulumi.Input<string>;
    /**
     * Any text you want that better describes this resource
     */
    description?: pulumi.Input<string>;
    message?: pulumi.Input<string>;
    /**
     * A unique name
     */
    name?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    networkData?: pulumi.Input<string>;
    networkDataBase64?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.CloudinitSecretTimeouts>;
    userData?: pulumi.Input<string>;
    userDataBase64?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudinitSecret resource.
 */
export interface CloudinitSecretArgs {
    cloudinitSecretId?: pulumi.Input<string>;
    /**
     * Any text you want that better describes this resource
     */
    description?: pulumi.Input<string>;
    /**
     * A unique name
     */
    name?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    networkData?: pulumi.Input<string>;
    networkDataBase64?: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.CloudinitSecretTimeouts>;
    userData?: pulumi.Input<string>;
    userDataBase64?: pulumi.Input<string>;
}
