// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCloudinitSecret(args: GetCloudinitSecretArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudinitSecretResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harvester:index/getCloudinitSecret:getCloudinitSecret", {
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCloudinitSecret.
 */
export interface GetCloudinitSecretArgs {
    id?: string;
    name: string;
    namespace?: string;
}

/**
 * A collection of values returned by getCloudinitSecret.
 */
export interface GetCloudinitSecretResult {
    readonly description: string;
    readonly id: string;
    readonly message: string;
    readonly name: string;
    readonly namespace?: string;
    readonly networkData: string;
    readonly networkDataBase64: string;
    readonly state: string;
    readonly tags: {[key: string]: string};
    readonly userData: string;
    readonly userDataBase64: string;
}
export function getCloudinitSecretOutput(args: GetCloudinitSecretOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCloudinitSecretResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harvester:index/getCloudinitSecret:getCloudinitSecret", {
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getCloudinitSecret.
 */
export interface GetCloudinitSecretOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
}
