// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getClusternetwork(args: GetClusternetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetClusternetworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harvester:index/getClusternetwork:getClusternetwork", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusternetwork.
 */
export interface GetClusternetworkArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getClusternetwork.
 */
export interface GetClusternetworkResult {
    readonly description: string;
    readonly id: string;
    readonly message: string;
    readonly name: string;
    readonly state: string;
    readonly tags: {[key: string]: string};
}
export function getClusternetworkOutput(args: GetClusternetworkOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusternetworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harvester:index/getClusternetwork:getClusternetwork", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusternetwork.
 */
export interface GetClusternetworkOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
