// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getImage(args?: GetImageArgs, opts?: pulumi.InvokeOptions): Promise<GetImageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harvester:index/getImage:getImage", {
        "displayName": args.displayName,
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImage.
 */
export interface GetImageArgs {
    displayName?: string;
    id?: string;
    name?: string;
    namespace?: string;
}

/**
 * A collection of values returned by getImage.
 */
export interface GetImageResult {
    readonly description: string;
    readonly displayName?: string;
    readonly id: string;
    readonly message: string;
    readonly name?: string;
    readonly namespace?: string;
    readonly progress: number;
    readonly pvcName: string;
    readonly pvcNamespace: string;
    readonly size: number;
    readonly sourceType: string;
    readonly state: string;
    readonly storageClassName: string;
    readonly storageClassParameters: {[key: string]: string};
    readonly tags: {[key: string]: string};
    readonly url: string;
    readonly volumeStorageClassName: string;
}
export function getImageOutput(args?: GetImageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harvester:index/getImage:getImage", {
        "displayName": args.displayName,
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImage.
 */
export interface GetImageOutputArgs {
    displayName?: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
}
