// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSetting(args: GetSettingArgs, opts?: pulumi.InvokeOptions): Promise<GetSettingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harvester:index/getSetting:getSetting", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSetting.
 */
export interface GetSettingArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getSetting.
 */
export interface GetSettingResult {
    readonly description: string;
    readonly id: string;
    readonly message: string;
    readonly name: string;
    readonly state: string;
    readonly tags: {[key: string]: string};
    readonly value: string;
}
export function getSettingOutput(args: GetSettingOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSettingResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harvester:index/getSetting:getSetting", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSetting.
 */
export interface GetSettingOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
