// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVlanconfig(args: GetVlanconfigArgs, opts?: pulumi.InvokeOptions): Promise<GetVlanconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("harvester:index/getVlanconfig:getVlanconfig", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVlanconfig.
 */
export interface GetVlanconfigArgs {
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getVlanconfig.
 */
export interface GetVlanconfigResult {
    readonly clusterNetworkName: string;
    readonly description: string;
    readonly id: string;
    readonly matchedNodes: string[];
    readonly message: string;
    readonly name: string;
    readonly nodeSelector: {[key: string]: string};
    readonly state: string;
    readonly tags: {[key: string]: string};
    readonly uplinks: outputs.GetVlanconfigUplink[];
}
export function getVlanconfigOutput(args: GetVlanconfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVlanconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("harvester:index/getVlanconfig:getVlanconfig", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVlanconfig.
 */
export interface GetVlanconfigOutputArgs {
    id?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
