// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Vlanconfig extends pulumi.CustomResource {
    /**
     * Get an existing Vlanconfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VlanconfigState, opts?: pulumi.CustomResourceOptions): Vlanconfig {
        return new Vlanconfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harvester:index/vlanconfig:Vlanconfig';

    /**
     * Returns true if the given object is an instance of Vlanconfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vlanconfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vlanconfig.__pulumiType;
    }

    /**
     * mgmt is a built-in cluster network and does not support creating/updating network configs.
     */
    public readonly clusterNetworkName!: pulumi.Output<string>;
    /**
     * Any text you want that better describes this resource
     */
    public readonly description!: pulumi.Output<string | undefined>;
    public /*out*/ readonly matchedNodes!: pulumi.Output<string[]>;
    public /*out*/ readonly message!: pulumi.Output<string>;
    /**
     * A unique name
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
     */
    public readonly nodeSelector!: pulumi.Output<{[key: string]: string} | undefined>;
    public /*out*/ readonly state!: pulumi.Output<string>;
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly timeouts!: pulumi.Output<outputs.VlanconfigTimeouts | undefined>;
    public readonly uplink!: pulumi.Output<outputs.VlanconfigUplink>;
    public readonly vlanconfigId!: pulumi.Output<string>;

    /**
     * Create a Vlanconfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VlanconfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VlanconfigArgs | VlanconfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VlanconfigState | undefined;
            resourceInputs["clusterNetworkName"] = state ? state.clusterNetworkName : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["matchedNodes"] = state ? state.matchedNodes : undefined;
            resourceInputs["message"] = state ? state.message : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["nodeSelector"] = state ? state.nodeSelector : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["timeouts"] = state ? state.timeouts : undefined;
            resourceInputs["uplink"] = state ? state.uplink : undefined;
            resourceInputs["vlanconfigId"] = state ? state.vlanconfigId : undefined;
        } else {
            const args = argsOrState as VlanconfigArgs | undefined;
            if ((!args || args.clusterNetworkName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clusterNetworkName'");
            }
            if ((!args || args.uplink === undefined) && !opts.urn) {
                throw new Error("Missing required property 'uplink'");
            }
            resourceInputs["clusterNetworkName"] = args ? args.clusterNetworkName : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["nodeSelector"] = args ? args.nodeSelector : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["timeouts"] = args ? args.timeouts : undefined;
            resourceInputs["uplink"] = args ? args.uplink : undefined;
            resourceInputs["vlanconfigId"] = args ? args.vlanconfigId : undefined;
            resourceInputs["matchedNodes"] = undefined /*out*/;
            resourceInputs["message"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vlanconfig.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Vlanconfig resources.
 */
export interface VlanconfigState {
    /**
     * mgmt is a built-in cluster network and does not support creating/updating network configs.
     */
    clusterNetworkName?: pulumi.Input<string>;
    /**
     * Any text you want that better describes this resource
     */
    description?: pulumi.Input<string>;
    matchedNodes?: pulumi.Input<pulumi.Input<string>[]>;
    message?: pulumi.Input<string>;
    /**
     * A unique name
     */
    name?: pulumi.Input<string>;
    /**
     * refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
     */
    nodeSelector?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    state?: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.VlanconfigTimeouts>;
    uplink?: pulumi.Input<inputs.VlanconfigUplink>;
    vlanconfigId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Vlanconfig resource.
 */
export interface VlanconfigArgs {
    /**
     * mgmt is a built-in cluster network and does not support creating/updating network configs.
     */
    clusterNetworkName: pulumi.Input<string>;
    /**
     * Any text you want that better describes this resource
     */
    description?: pulumi.Input<string>;
    /**
     * A unique name
     */
    name?: pulumi.Input<string>;
    /**
     * refer to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
     */
    nodeSelector?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.VlanconfigTimeouts>;
    uplink: pulumi.Input<inputs.VlanconfigUplink>;
    vlanconfigId?: pulumi.Input<string>;
}
