harbor:
  url: ""
  username: "admin"
  password: "Harbor12345"
project:
  name: "application-collection"

registries:
  - name: "docker.io"
    url: "https://registry-1.docker.io"
    type: "docker-registry"
    insecure: false
    #credential:
    #  type: "basic"
    #  access_key: "<YOUR_DOCKER_IO_USER>"
    #  access_secret: "<YOUR_DOCKER_IO_PASS>"

  - name: "ghcr.io"
    url: "https://ghcr.io"
    type: "docker-registry"
    insecure: false
    #credential:
    #  type: "basic"
    #  access_key: "<YOUR_GHCR_USER>"
    #  access_secret: "<YOUR_GHCR_PASS>"

  - name: "quay.io"
    url: "https://quay.io"
    type: "docker-registry"
    insecure: false
    #credential:
    #  type: "basic"
    #  access_key: "<YOUR_QUAY_USER>"
    #  access_secret: "<YOUR_QUAY_PASS>"

  - name: "registry.suse.com"
    url: "http://registry.suse.com"
    type: "docker-registry"
    insecure: true


  - name: "registry.rancher.com"
    url: "http://registry.rancher.com"
    type: "docker-registry"
    insecure: false
