// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudinitSecretTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface ClusternetworkTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface ImageTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface NetworkTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface SettingTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface SshKeyTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface StorageclassTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface VirtualmachineCloudinit {
    networkData?: pulumi.Input<string>;
    networkDataBase64?: pulumi.Input<string>;
    networkDataSecretName?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    userData?: pulumi.Input<string>;
    userDataBase64?: pulumi.Input<string>;
    userDataSecretName?: pulumi.Input<string>;
}

export interface VirtualmachineDisk {
    accessMode?: pulumi.Input<string>;
    autoDelete?: pulumi.Input<boolean>;
    bootOrder?: pulumi.Input<number>;
    bus?: pulumi.Input<string>;
    containerImageName?: pulumi.Input<string>;
    existingVolumeName?: pulumi.Input<string>;
    hotPlug?: pulumi.Input<boolean>;
    image?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    size?: pulumi.Input<string>;
    storageClassName?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    volumeMode?: pulumi.Input<string>;
    volumeName?: pulumi.Input<string>;
}

export interface VirtualmachineInput {
    bus?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}

export interface VirtualmachineNetworkInterface {
    interfaceName?: pulumi.Input<string>;
    ipAddress?: pulumi.Input<string>;
    macAddress?: pulumi.Input<string>;
    model?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    /**
     * if the value is empty, management network is used
     */
    networkName?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    /**
     * wait for this network interface to obtain an IP address. If a non-management network is used, this feature requires qemu-guest-agent installed and started in the VM, otherwise, VM creation will stuck until timeout
     */
    waitForLease?: pulumi.Input<boolean>;
}

export interface VirtualmachineTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface VirtualmachineTpm {
    /**
     * just add this field for doc generation
     */
    name?: pulumi.Input<string>;
}

export interface VlanconfigTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}

export interface VlanconfigUplink {
    /**
     * refer to https://www.kernel.org/doc/Documentation/networking/bonding.txt
     */
    bondMiimon?: pulumi.Input<number>;
    bondMode?: pulumi.Input<string>;
    mtu?: pulumi.Input<number>;
    nics: pulumi.Input<pulumi.Input<string>[]>;
}

export interface VolumeTimeouts {
    create?: pulumi.Input<string>;
    default?: pulumi.Input<string>;
    delete?: pulumi.Input<string>;
    read?: pulumi.Input<string>;
    update?: pulumi.Input<string>;
}
