// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CloudinitSecretTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface ClusternetworkTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface GetVirtualmachineCloudinit {
    networkData: string;
    networkDataBase64: string;
    networkDataSecretName: string;
    type: string;
    userData: string;
    userDataBase64: string;
    userDataSecretName: string;
}

export interface GetVirtualmachineDisk {
    accessMode: string;
    autoDelete: boolean;
    bootOrder: number;
    bus: string;
    containerImageName: string;
    existingVolumeName: string;
    hotPlug: boolean;
    image: string;
    name: string;
    size: string;
    storageClassName: string;
    type: string;
    volumeMode: string;
    volumeName: string;
}

export interface GetVirtualmachineInput {
    bus: string;
    name: string;
    type: string;
}

export interface GetVirtualmachineNetworkInterface {
    interfaceName: string;
    ipAddress: string;
    macAddress: string;
    model: string;
    name: string;
    networkName: string;
    type: string;
    waitForLease: boolean;
}

export interface GetVirtualmachineTpm {
    name: string;
}

export interface GetVlanconfigUplink {
    bondMiimon: number;
    bondMode: string;
    mtu: number;
    nics: string[];
}

export interface ImageTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface NetworkTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface SettingTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface SshKeyTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface StorageclassTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface VirtualmachineCloudinit {
    networkData?: string;
    networkDataBase64?: string;
    networkDataSecretName?: string;
    type?: string;
    userData?: string;
    userDataBase64?: string;
    userDataSecretName?: string;
}

export interface VirtualmachineDisk {
    accessMode: string;
    autoDelete: boolean;
    bootOrder?: number;
    bus: string;
    containerImageName?: string;
    existingVolumeName?: string;
    hotPlug: boolean;
    image?: string;
    name: string;
    size?: string;
    storageClassName: string;
    type?: string;
    volumeMode: string;
    volumeName: string;
}

export interface VirtualmachineInput {
    bus?: string;
    name: string;
    type?: string;
}

export interface VirtualmachineNetworkInterface {
    interfaceName: string;
    ipAddress: string;
    macAddress: string;
    model?: string;
    name: string;
    /**
     * if the value is empty, management network is used
     */
    networkName?: string;
    type: string;
    /**
     * wait for this network interface to obtain an IP address. If a non-management network is used, this feature requires qemu-guest-agent installed and started in the VM, otherwise, VM creation will stuck until timeout
     */
    waitForLease?: boolean;
}

export interface VirtualmachineTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface VirtualmachineTpm {
    /**
     * just add this field for doc generation
     */
    name?: string;
}

export interface VlanconfigTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

export interface VlanconfigUplink {
    /**
     * refer to https://www.kernel.org/doc/Documentation/networking/bonding.txt
     */
    bondMiimon?: number;
    bondMode?: string;
    mtu?: number;
    nics: string[];
}

export interface VolumeTimeouts {
    create?: string;
    default?: string;
    delete?: string;
    read?: string;
    update?: string;
}

