// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("harvester");

/**
 * kubeconfig file path or content of the kubeconfig file as base64 encoded string, users can use the KUBECONFIG
 * environment variable instead.
 */
export declare const kubeconfig: string | undefined;
Object.defineProperty(exports, "kubeconfig", {
    get() {
        return __config.get("kubeconfig");
    },
    enumerable: true,
});

/**
 * name of the kubernetes context to use
 */
export declare const kubecontext: string | undefined;
Object.defineProperty(exports, "kubecontext", {
    get() {
        return __config.get("kubecontext");
    },
    enumerable: true,
});

