{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.username }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username .Values.token | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $registryAuthMap := dict .Values.registry $registryAuthDocument }}
{{- $dockerConfigJson := dict "auths" $registryAuthMap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: cattle-system
  annotations:
    sprouter.geeko.me/enabled: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfigJson | toJson | b64enc | quote }}
