apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-setup-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: harbor-setup
          image: opensuse/tumbleweed
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -euo pipefail
              zypper install -y jq

              {{- range .Values.registries }}
              echo "👉  Creating proxy cache for {{ .name }}…"

              # 1) create the registry
              curl -X POST \
                -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" \
                -H "Content-Type: application/json" \
                --url "https://${HARBOR_URL}/api/v2.0/registries" \
                -d @- <<EOF
              {
              {{- with .credential }}
                {{- if and .access_key .access_secret }}
                "credential": {
                  "access_key": "{{ .access_key }}",
                  "access_secret": "{{ .access_secret }}",
                  "type": {{ .type | quote }}
                },
                {{- end }}
              {{- end }}
                "insecure": {{ .insecure }},
                "name": {{ .name | quote }},
                "type": {{ .type | quote }},
                "url": {{ .url | quote }}
              }
              EOF

              # 2) grab the new registry's ID
              REG_ID=$(curl -s \
                -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" \
                --url "https://${HARBOR_URL}/api/v2.0/registries" \
                | jq -r '.[] | select(.name=="{{ .name }}") | .id')

              # 3) create a project named the same as the registry, linked to that registry ID
              echo "👉  Creating project {{ .name }}…"
              curl -X POST \
                -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" \
                -H "Content-Type: application/json" \
                --url "https://${HARBOR_URL}/api/v2.0/projects" \
                -d @- <<EOP
              {
                "project_name": {{ .name | quote }},
                "registry_id": $REG_ID,
                "public": true
              }
              EOP

              echo "✅  Done {{ .name }}"
              {{- end }}
          env:
            - name: HARBOR_USERNAME
              value: {{ .Values.harbor.username | quote }}
            - name: HARBOR_PASSWORD
              value: {{ .Values.harbor.password | quote }}
            - name: HARBOR_URL
              value: {{ .Values.harbor.url | quote }}
